# Generated by Django 3.0.6 on 2020-07-05 17:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20200523_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 7, 5, 17, 36, 36, 361748, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
