# Generated by Django 3.0.6 on 2020-07-05 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_auto_20200705_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='songs',
        ),
    ]
