# Generated by Django 3.0.6 on 2020-07-05 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_remove_album_songs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlbumSong',
        ),
    ]
