# Generated by Django 3.0.6 on 2020-06-10 12:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playlist', '0002_auto_20200608_1829'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playlist',
            unique_together={('name', 'owner')},
        ),
    ]
