# Generated by Django 3.0.6 on 2020-07-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0004_auto_20200610_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='cover',
            field=models.ImageField(null=True, upload_to='playlist/cover/'),
        ),
    ]
