# Generated by Django 3.0.6 on 2020-07-01 18:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0005_playlist_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 7, 1, 18, 27, 44, 923733, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlistsong',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 7, 1, 18, 27, 50, 594765, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
