# Generated by Django 3.0.6 on 2020-07-05 17:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0002_auto_20200616_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 7, 5, 17, 35, 0, 833057, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
