# Generated by Django 3.0.6 on 2020-06-16 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_auto_20200616_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='genere',
        ),
    ]
