# Generated by Django 3.0.6 on 2020-06-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0003_remove_song_genere'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='genere',
            field=models.ManyToManyField(through='song.SongGenere', to='song.Genere'),
        ),
    ]
