# Generated by Django 3.0.6 on 2020-06-16 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0001_initial'),
        ('song', '0004_song_genere'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SongGenere',
            new_name='SongGenre',
        ),
        migrations.RemoveField(
            model_name='song',
            name='genere',
        ),
        migrations.RemoveField(
            model_name='songgenre',
            name='genere',
        ),
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.ManyToManyField(through='song.SongGenre', to='genre.Genre'),
        ),
        migrations.AddField(
            model_name='songgenre',
            name='genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='genre.Genre'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Genere',
        ),
    ]
