# Generated by Django 3.0.6 on 2020-06-16 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0001_initial'),
        ('song', '0005_auto_20200616_1239'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='songgenre',
            unique_together={('song', 'genre')},
        ),
    ]
