# Generated by Django 3.0.6 on 2020-07-05 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0004_artist_date_created'),
        ('song', '0007_songgenre_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='artist.Artist'),
            preserve_default=False,
        ),
    ]
