# Generated by Django 3.0.6 on 2020-07-05 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0005_delete_albumsong'),
        ('song', '0008_song_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='album.Album'),
            preserve_default=False,
        ),
    ]
